version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: "2.x"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: "2.x"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: "master"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: "master"
